name: Node.js CI

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  # Задача для установки зависимостей
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # действие actions/checkout@v3 автоматически выполняет клонирование кода из репозитория
      - name: Set up Node.js
        uses: actions/setup-node@v3 # действие actions/setup-node@v3 помогает установить Node.js нужной версии
        with:
         node-version: '16'

      - name: Install dependencies
        run: npm install
  # Задача тестирования на Linux
  test_linux:
        runs-on: ubuntu-latest
        needs: install # Выполняется после установки зависимостей (install)
        steps:
          - name: Install dependencies
            run: npm ci --legacy-peer-deps --no-audit --force --verbose # Устанавливает зависимости из lock-файла
          - name: Run tests
            run: npm test
