
name: Node.js CI

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  # Задача для установки зависимостей
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # действие actions/checkout@v3 автоматически выполняет клонирование кода из репозитория
      - name: Set up Node.js
        uses: actions/setup-node@v6 # действие actions/setup-node@v3 помогает установить Node.js нужной версии
        with:
         node-version: '18'

      - name: Install dependencies
        run: npm install
  # Задача тестирования на Linux
  test_linux:
    runs-on: ubuntu-latest
    needs: install # Выполняется после установки зависимостей (install)
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # действие actions/checkout@v3 автоматически выполняет клонирование кода из репозитория
      - name: Set up Node.js
        uses: actions/setup-node@v6 # действие actions/setup-node@v3 помогает установить Node.js нужной версии
        with:
         node-version: '18'
    #  - name: Install dependencies
    #    run: npm install
      - name: Install dependencies
        run: npm ci --legacy-peer-deps --no-audit --force --verbose # Устанавливает зависимости из lock-файла
      - name: Run tests
        run: npm test
  # Задача тестирования на Windows
  test_windows:
    runs-on: windows-latest
    needs: install # Выполняется после установки зависимостей (install)
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # действие actions/checkout@v3 автоматически выполняет клонирование кода из репозитория
      - name: Set up Node.js
        uses: actions/setup-node@v6 # действие actions/setup-node@v3 помогает установить Node.js нужной версии
        with:
         node-version: '18'
    #  - name: Install dependencies
    #    run: npm install
      - name: Install dependencies
        run: npm ci --legacy-peer-deps --no-audit --force --verbose # Устанавливает зависимости из lock-файла
      - name: Run tests
        run: npm test
  # Задача тестирования на MacOS
  test_macos:
    runs-on: macos-latest
    needs: install # Выполняется после установки зависимостей (install)
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # действие actions/checkout@v3 автоматически выполняет клонирование кода из репозитория
      - name: Set up Node.js
        uses: actions/setup-node@v6 # действие actions/setup-node@v3 помогает установить Node.js нужной версии
        with:
         node-version: '18'
    #  - name: Install dependencies
    #    run: npm install
      - name: Install dependencies
        run: npm ci --legacy-peer-deps --no-audit --force --verbose # Устанавливает зависимости из lock-файла
      - name: Run tests
        run: npm test
  # Задача сборки и деплоя проекта
  publish-gpr:
    needs: [install, test_linux, test_windows, test_macos]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '18'
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
